logging:
  level:
    root: debug
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    # com.itmuch.youran.persistence: ERROR