server:
  #port: 8501
  port: 8765
spring:
  application:
    name: microservice-zuul
  #cloud:
  #  config:
  #    discovery:
  #      enabled: true
  #      service-id: microservice-config-server
  #    fail-fast: true
  #    username: root
  #    password: root
  #    profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true
   # instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
    appname: microservice-zuul
zuul:
  ignored-services: "*"
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  prefix: #为zuul设置一个公共的前缀
    #ratelimit: # 网关限流
    #  key-prefix: gate_rate
    #  enabled: true
    #  repository: REDIS #REDIS, JPA, IN_MEMORY
    #  behind-proxy: true
    #  default-policy: #optional - will apply unless specific policy exists
    #    limit: 200
    #    refresh-interval: 60 #default value (in seconds)
    #    type: #optional
    #      - user
    #      - origin
    #      - url
  routes:
    #test:
    #  path: /api/auth/jwt/token/**
    #  url: forward:/local
    #microservice-consumer-h5-feign: /consumer/**
    microservice-security-server: /api/auth/**
    microservice-provider-userservice: /api/admin/**
ribbon:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  eureka:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  #httpclient:
  #  enabled: false
  #okhttp:
  #  enabled: true
gate:
  ignore:
    startWith: /static,/api/auth/jwt


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE
auth:
  serviceId: microservice-security-server
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: microservice-zuul  #不填则默认读取spring.application.name
    secret: cNNnCEYj
logging:
    level:
#        tk.mybatis: DEBUG
        com.qiu: DEBUG